[target.riscv64gc-unknown-none-elf]
runner = """
qemu-system-riscv64 -machine virt -bios none -m 524M -smp 4 -nographic \
-serial mon:stdio -global virtio-mmio.force-legacy=false \
-drive file=target/fs.img,if=none,format=raw,id=x0 \
-device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
-netdev user,id=net0,net=192.0.2.0/24,host=192.0.2.1,dhcpstart=192.0.2.2,hostfwd=tcp::7070-:7,hostfwd=tcp::8080-:8080 \
-device virtio-net-device,netdev=net0,bus=virtio-mmio-bus.1 \
-kernel
"""
